---

- name: Install git
  package:
    name: git
    state: latest

- name: Checkout ecopoiesis-utility
  git:
    repo: https://github.com/antonym/ecopoiesis-utility
    dest: /opt/ecopoiesis-utility
    version: master
    force: true

- name: Install ecopoiesis-utility startup
  copy:
    src: ecopoiesis-utility
    dest: /usr/local/bin/ecopoiesis-utility
    mode: 0744

- name: Install ecopoiesis-utility service file
  copy:
    src: ecopoiesis-utility.service
    dest: /etc/systemd/system/ecopoiesis-utility.service
    mode: 0744

- name: Enable startup service
  systemd:
    name: ecopoiesis-utility
    daemon_reload: yes
    enabled: yes
